trigger:
  batch: true
  branches:
    include:
    - '*'

  tags:
    include:
      - v*.*
      - prod

stages:
- stage: onPush
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r unit-requirements.txt
        pip install tools/dbx-0.7.0-py3-none-any.whl
        pip install -e .
      displayName: 'Install dependencies'

    - script: |
        pytest tests/unit
      displayName: 'Run Unit tests'

    - script: |
        echo "[{{cookiecutter.profile}}]" >> ~/.databrickscfg
        echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
        echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Prepare profile'

    - script: |
        dbx deploy --jobs={{cookiecutter.project_slug}}-sample-integration-test
      displayName: 'Deploy integration test'

    - script: |
        dbx launch --job={{cookiecutter.project_slug}}-sample-integration-test --trace
      displayName: 'Launch integration on test'

- stage: onRelease
  condition: |
    or(
      startsWith(variables['Build.SourceBranch'], 'refs/heads/releases'),
      startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    )
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: env | sort
        displayName: 'Environment / Context'

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: 3.7

      - checkout: self
        persistCredentials: true
        clean: true
        displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

      - script: |
          python -m pip install --upgrade pip
          pip install -r unit-requirements.txt
          pip install tools/dbx-0.7.0-py3-none-any.whl
          pip install -e .
        displayName: 'Install dependencies'

      - script: |
          pytest tests/unit
        displayName: 'Run Unit tests'

      - script: |
          echo "[{{cookiecutter.profile}}]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
        env:
          DATABRICKS_HOST: $(DATABRICKS_HOST)
          DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        displayName: 'Prepare profile'

      - script: |
          dbx deploy --jobs={{cookiecutter.project_slug}}-sample-integration-test
        displayName: 'Deploy integration test'

      - script: |
          dbx launch --job={{cookiecutter.project_slug}}-sample-integration-test --trace
        displayName: 'Launch integration on test'

      - script: |
          dbx deploy --jobs={{cookiecutter.project_slug}}-sample
        displayName: 'Deploy the job'